# Generated by Django 4.0.3 on 2022-09-13 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='canceled',
            new_name='is_canceled',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='finished',
            new_name='is_finished',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='vip',
            new_name='is_vip',
        ),
    ]
