# Generated by Django 4.0.3 on 2022-09-13 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0002_rename_canceled_appointment_is_canceled_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='is_canceled',
            new_name='canceled',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='is_finished',
            new_name='finished',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='is_vip',
            new_name='vip',
        ),
    ]
